### PR TITLE
Fix trailing comma support in generics

### LINKED ISSUE #31: local ambiguity: multiple parsing options: built-in NTs tt ('generics') or 1 other option
got error "local ambiguity: multiple parsing options: built-in NTs tt ('generics') or 1 other option" with version 0.1.8

code that fails looks like:

```rust

pin_project_lite::pin_project! {
#[doc(hidden)]
pub struct HttpServiceResponse<
    T,
    S: ServiceFactory,
    B,
    X: ServiceFactory,
    U: ServiceFactory,
> {
...
}}
```

### PR DESCRIPTION
**Pull request by taiki-e**
This reverts commit 950229ce95463fe15e7f2b5a4de94870d499c0f6.

Fixes #31

### CODE REVIEW

File: tests/test.rs [hunk 1]
```diff
@@ -385,3 +385,51 @@ fn no_infer_outlives() {
...
+    }
+
+    // pin_project! {
+    //     pub struct S4<
+    //         'a,
+    //         'b: 'a, // <-----
+    //     > {
+    //         f: &'a &'b (),
+    //     }
+    // }
```
Comment (taiki-e) [inline tests/test.rs:434]: This code doesn't seem to compile even in previous versions.
